language: go

go:
  - 1.7.x
  - 1.8.x
  - 1.9.x

go_import_path: github.com/antchfx/antch

before_install:
  - go get github.com/mattn/goveralls

script:
  - wget -O dep https://github.com/golang/dep/releases/download/v0.3.2/dep-linux-amd64
  - chmod +x dep
  - ./dep ensure
  - $GOPATH/bin/goveralls -service=travis-ci